import {
  LucideIcon,
  Check,
  House,
  Box,
  Diamond,
  User,
  Banknote,
  MessageCircleQuestion,
  Calendar,
  ArrowUpRight,
  CreditCard,
  Settings,
  ArrowLeft,
  Coins,
  Sun,
  Moon,
  Laptop,
  Instagram,
  Linkedin,
  Twitter,
  BarChart,
  LogOut,
  Database,
  Mail,
  Link,
} from "lucide-react"

import {
  FacebookSVG,
  RedditSVG,
  SnapchatSVG,
  SpotifySVG,
  TelegramSVG,
  ThreadsSVG,
  TiktokSVG,
  WebsiteSVG,
  WhatsAppSVG,
  YoutubeSVG,
} from "./svgs"

export type Icon = LucideIcon | SVGElement
export type SocialIcon = LucideIcon | SVGElement

export const Icons = {
  check: Check,
  home: House,
  decks: Box,
  roadmap: Diamond,
  user: User,
  banknote: Banknote,
  question: MessageCircleQuestion,
  calendar: Calendar,
  arrowUpRight: ArrowUpRight,
  creditCard: CreditCard,
  settings: Settings,
  arrowLeft: ArrowLeft,
  coins: Coins,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  chart: BarChart,
  logout: LogOut,
  data: Database,
  instagram: Instagram,
  linkedin: Linkedin,
  x: Twitter,
}

export const SocialIcons = {
  instagram: Instagram,
  linkedin: Linkedin,
  x: Twitter,
  website: () => WebsiteSVG,
  email: Mail,
  facebook: () => FacebookSVG,
  reddit: () => RedditSVG,
  whatsapp: () => WhatsAppSVG,
  spotify_artist: () => SpotifySVG,
  spotify_user: () => SpotifySVG,
  youtube: () => YoutubeSVG,
  telegram: () => TelegramSVG,
  snapchat: () => SnapchatSVG,
  threads: () => ThreadsSVG,
  tiktok: () => TiktokSVG,
  custom: Link,
}
